using SpaceGame.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpaceGame.BaseClasses
{
    public enum ItemCategoryEnum
    {
        None,
        PlayerWeapon,
        PlayerArmor,
        ShipWeapon,
        ShipArmor,
        LanderWeapon,
        LanderArmor
    }

    public class ItemCategory : BaseState<ItemCategory, ItemCategoryEnum>
    {
        private ItemCategory(ItemCategoryEnum state) : base(state) { }

        public static readonly ItemCategory None = new ItemCategory(ItemCategoryEnum.None);
        public static readonly ItemCategory PlayerWeapon = new ItemCategory(ItemCategoryEnum.PlayerWeapon);
        public static readonly ItemCategory PlayerArmor = new ItemCategory(ItemCategoryEnum.PlayerArmor);
        public static readonly ItemCategory ShipWeapon = new ItemCategory(ItemCategoryEnum.ShipWeapon);
        public static readonly ItemCategory ShipArmor = new ItemCategory(ItemCategoryEnum.ShipArmor);
        public static readonly ItemCategory LanderWeapon = new ItemCategory(ItemCategoryEnum.LanderWeapon);
        public static readonly ItemCategory LanderArmor = new ItemCategory(ItemCategoryEnum.LanderArmor);
    }

    internal class InventoryItem
    {
        public string Name {  get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;

        // How much damage is generated by this item
        public int Damage { get; set; }

        // How much protection is generated by this item
        public int Protection {  get; set; }

        // The monetary/trade value of the item
        public int Value { get; set; }

        public ItemCategory ItemCategory { get; set; } = ItemCategory.None;
    }
}
